title: Emilie Drouin
description: Carnet de doctorat et de recherche
url: "http://emidrouin.ca/"
baseurl: ""

markdown: kramdown

tracking_id: #
github_username: emidrouin
orcid:  https://orcid.org/0000-0001-6336-5312

footer: yes

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "à propos"
   link: "/"
 - name: "thèse"
   link: "these.md"
 - name: "CV"
   link: "cv.md"
